name: Backend system tests

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"

jobs:
  system-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
      - name: Install Dependencies
        working-directory: ./backend
        run: pnpm install --frozen-lockfile
      - name: Run Server and Test with Newman
        working-directory: ./backend
        run: pnpm run test:system
